server:
  port: 8888

spring:
  application:
    name: config-service
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest
  profiles:
    active: native
  cloud:
    config:
      server:
        native:
          search-locations: file://${user.home}/spring/msa/native-repo
        git:
          uri: https://github.com/sunjuyoung/spring-cloud-config.git
#          username:
#          password:
#          uri: file:///D:/git-local-repo
management:
  endpoints:
    web:
      exposure:
        include: health, busrefresh
